Net/ThemeName "Matcha-dark-azul"
Net/IconThemeName "bloom"
Gtk/CursorThemeName "xcursor-breeze-snow"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
